from Activity_Guide_Changes.GaNChangesNorth import createNorthDir
from Activity_Guide_Changes.GaNChangesNorth import createNorthPaths
from Activity_Guide_Changes.GaNChangesNorth import importNorthData
from Activity_Guide_Changes.GaNChangesNorth import northTranslation
from Activity_Guide_Changes.GaNChangesSouth import createSouthDir
from Activity_Guide_Changes.GaNChangesSouth import createSouthPaths
from Activity_Guide_Changes.GaNChangesSouth import southTranslation
from Activity_Guide_Changes.GaNGetImages import createImageDir
from Activity_Guide_Changes.GaNGetImages import imagesLinks
from Activity_Guide_Changes.GaNGetImages import imageDownload
from Activity_Guide_Changes.GaNPrintImages import openWordDoc
from Activity_Guide_Changes.GaNPrintImages import transformLatitude
from Activity_Guide_Changes.GaNPrintImages import openImage
from Activity_Guide_Changes.GaNPrintImages import printImage



